pipeline {
  agent any

  environment {
    IMAGE = "raja4123/simple-app"
  }

  stages {
    stage('Build Docker Image') {
      steps {
        dir('simple-windows_terraform_with jenkins and docker/app') {
          bat 'echo Building image: %IMAGE%'
          bat 'dir'
          bat 'docker build -t %IMAGE% .'
        }
      }
    }

    stage('Push to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
          bat 'echo %PASS% | docker login -u %USER% --password-stdin'
          bat 'docker push %IMAGE%'
        }
      }
    }

    stage('Deploy with Terraform') {
      steps {
        dir('terraform') {
          withCredentials([
            string(credentialsId: 'aws-access-key', variable: 'AWS_ACCESS_KEY_ID'),
            string(credentialsId: 'aws-secret-key', variable: 'AWS_SECRET_ACCESS_KEY')
          ]) {
            bat 'terraform init'
            bat 'terraform apply -auto-approve'
          }
        }
      }
    }
  }
}
