pipeline
{
  agent any
  stages {
    stage ('checkout'){
      steps {
           		echo 'cloning code from git'	
              git branch: 'main', url: 'https://github.com/Raja4123/My_Projects.git'

      }
    }
    stage ('docker build'){
      steps {
        echo 'building docker image'
        sh '''
         cd Flask_Docker_app
         docker build -t flaskapp .'''
      }
    }
    stage ('running container') {
      steps {
        echo 'running container'
        sh '''
            docker stop flaskapp || true
            docker rm flaskapp || true
            docker run -d --name flaskapp flaskapp
           '''
      }
    }
  }
}
